version: '3'

services:

  reverse-proxy:
    image: traefik:v2.0.0
    hostname: "{{.Node.Hostname}}"
    ports:
      - "80:80"
      - "443:443"
      - "6379:6379"
      - "6380:6380"
      - "6381:6381"
      - "6382:6382"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_net
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role == manager"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api_router.rule=Host(`traefik.local`) && ( PathPrefix(`/api`) || PathPrefix(`/dashboard`) )"
        - "traefik.http.routers.api_router.service=api@internal"
        - "traefik.http.routers.api_router.middlewares=api_auth"
        - "traefik.http.routers.api_router.entrypoints=http,https"
        - "traefik.http.services.api_service.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.api_auth.basicauth.users=admin:$$2y$$12$$li0NAdHVZ9l8zVyisuhRzuZKayhegzj49SZV66exjm/UtcMw.0FUa"

networks:
  proxy_net:
    external: true